import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import Navigationbar from "./navigationbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NextJS Activity",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundImage: 'url("/assets/image/background1.jpg")', backgroundSize: 'cover', backgroundPosition: 'center', minHeight: '100vh', color: 'white' }}>
        <Navigationbar />
        <div className="min-h-screen w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
